# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Devon Rachwal
title: Brewer
email: Devon@DevonRachwal.com
website: DevonRachwal.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  DevonRachwal
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: DevonRachwal
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Me.jpg
about_content: | # this will include new lines to allow paragraphs as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.
  Hi, my name is Devon I'm the Brewer at Whitedog Brewery, I have 3 years of College experience with a Comp Sci and Electrical Engineering class experience.

  I am most skilled in: <mark>JavaScript</mark>

content:
  - title: SkillSet # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: https://github.com/DevonRachwal
        # link_text: Project Website
       # additional_links:
          #
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
         # This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Ive started uploading finished projects over my years in school to my github. If you have questions about any of them feel free to ask. 
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: White Dog Brewing
        link: whitedogbrewing.com
        # link_text: Whitedog
        sub_title: Brewer
        caption: Febuary 2020 - Present
        #quote: >
         # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Worked with Whitedog ownership to produce and provide product for Whitedog Boise which lead to the expansion to Whitedog Caldwell. I currently brew for both locations. 
      - layout: left
        title: Learning Assistant
        link: https://www.boisestate.edu/aasc/academicsupportservices/boise-state-learning-assistant-program
        sub_title: Learning Assistant Calc I / Calc III
        caption: 2019 - 2020
        description: |
          Worked with hand with teachers and LA coordinaters, sat through classes and hosted tutoring sessions to help students study and learn.
          description: | # this will include new lines to allow paragraphs
          Worked with Whitedog ownership to produce and provide product for Whitedog Boise which lead to the expansion to Whitedog Caldwell. I currently brew for both locations. 
      - layout: left
        title: Satellite Communications Technician 
        # link: [Boise State LA Program](https://www.boisestate.edu/aasc/academicsupportservices/boise-state-learning-assistant-program/)
        # sub_title: Learning Assistant Calc I / Calc III
        caption: 2016 - 2018
        description: |
          Trained and supervised airmen on how to set up antennas to connect to satellites.
      - layout: left
        title: Radio Frequency Transmission Systems Specialist 
        # link: [Boise State LA Program](https://www.boisestate.edu/aasc/academicsupportservices/boise-state-learning-assistant-program/)
        # sub_title: Learning Assistant Calc I / Calc III
        caption: 2013 - 2016
        description: |
          Trained and supervised airmen on how to set up antennas to connect to satellites. 
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Boise State University
        caption: 2017 - 2019
        #sub_title: BSc Computer Science
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Went to school at Boise State University where I took many high level math classes, learned how to code, and some circuitry. 
      - layout: left
        title: Community College of the Air Force
        caption: 2013
        description: |
          Learned Electronic communications principals during my time seerving in the AirForce.



  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Basketball
      - Gaming
      - Running
      - Dog Dad
      

    #Look at this cool image  
    #![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
